// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0OjWPyd-qCoButAayU1vmc-ph66RN4Lc',
    appId: '1:412900967146:web:15c89a910bb6e014668d93',
    messagingSenderId: '412900967146',
    projectId: 'ttgo-iot-project',
    authDomain: 'ttgo-iot-project.firebaseapp.com',
    databaseURL: 'https://ttgo-iot-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ttgo-iot-project.firebasestorage.app',
    measurementId: 'G-1M9RBYWL5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwHnem3dmzFgdE3geTJ8C64Mzo33BNaR4',
    appId: '1:412900967146:android:479ea8acdb6f0a8c668d93',
    messagingSenderId: '412900967146',
    projectId: 'ttgo-iot-project',
    databaseURL: 'https://ttgo-iot-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ttgo-iot-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0OjWPyd-qCoButAayU1vmc-ph66RN4Lc',
    appId: '1:412900967146:web:17321f2485ae1c51668d93',
    messagingSenderId: '412900967146',
    projectId: 'ttgo-iot-project',
    authDomain: 'ttgo-iot-project.firebaseapp.com',
    databaseURL: 'https://ttgo-iot-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ttgo-iot-project.firebasestorage.app',
    measurementId: 'G-E7K1Z4XDEX',
  );
}
